Documentation:
  Enabled: false
Style/BlockDelimiters:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/MultilineBlockChain:
  Enabled: false
Style/NegatedIf:
  Exclude:
    - spec/*
Style/NumericLiterals:
  Enabled: false
Style/SignalException:
  Exclude:
    - spec/*
